# Etapa de construcción
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Etapa final
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/test-0.0.1-SNAPSHOT.jar /app/account.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/app/account.jar"]

