# Etapa de construcción
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Etapa final
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/test-0.0.1-SNAPSHOT.jar /app/customer.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/customer.jar"]
